#include "hal_data.h"
#include "common_utils.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
#include "bootloader.h"

void hal_entry(void)
{
    /* Check for magic word in backup registers to boot application */
    uint32_t magic_word = ((uint32_t)R_SYSTEM->VBTBKR[0] << 24) |
                          ((uint32_t)R_SYSTEM->VBTBKR[1] << 16) |
                          ((uint32_t)R_SYSTEM->VBTBKR[2] << 8)  |
                          ((uint32_t)R_SYSTEM->VBTBKR[3] << 0);

    if (magic_word == APP_VALID_MARKER)
    {
        /* Clear the magic word to avoid re-booting into the application on the next reset */
        R_SYSTEM->PRCR = (uint16_t) (0xA500 | 2); // Unlock system registers
        R_SYSTEM->VBTBKR[0] = 0;
        R_SYSTEM->VBTBKR[1] = 0;
        R_SYSTEM->VBTBKR[2] = 0;
        R_SYSTEM->VBTBKR[3] = 0;
        R_SYSTEM->PRCR = (uint16_t) (0xA500 | 0); // Lock system registers

        /* All peripherals are in a reset state, so we can jump directly. */
        
        /* 1. Disable all maskable interrupts */
        __disable_irq();

        /* 2. Clear all pending interrupts in the NVIC */
        for (IRQn_Type i = 0; i < 96; i++)
        {
            NVIC_ClearPendingIRQ(i);
        }

        /* 3. Set the main stack pointer from the application's vector table */
        __set_MSP(*(uint32_t *)APP_FIRMWARE_START_ADDRESS);

        /* 4. Get the application's reset handler address from the vector table */
        void (*app_reset_handler)(void) = (void (*)(void))(*(uint32_t *)(APP_FIRMWARE_START_ADDRESS + 4));

        /* 5. Jump to the application's reset handler */
        app_reset_handler();
    }
    else
    {
        /* No valid application marker found, proceed with bootloader */
        bootloader_init(); // This initializes CAN and prints a startup message

        SEGGER_RTT_printf(0, "\r\nPress '1' for CAN update, or '2' for UART (.hex) update...\r\n");

        char rx_char = 0;
        while (1)
        {
            /* Check for user input from RTT */
            if (SEGGER_RTT_HasKey())
            {
                rx_char = (char)SEGGER_RTT_GetKey();
                if ('1' == rx_char)
                {
                    SEGGER_RTT_printf(0, "CAN mode selected. Waiting for firmware packets...\r\n");
                    /* The bootloader now waits for CAN messages indefinitely via interrupts */
                    while(1)
                    {
                         /* The CAN callback will handle everything. */
                    }
                }
                else if ('2' == rx_char)
                {
                    SEGGER_RTT_printf(0, "UART mode selected. Send .hex file now...\r\n");
                    bootloader_uart_mode(); // This function will contain the UART loop
                }
                else
                {
                    SEGGER_RTT_printf(0, "Invalid selection. Press '1' or '2'.\r\n");
                }
            }
        }
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
